public class Constants {
    public static final String OBJECT_FIELD_VALUE_FLIGHT_STATUS_DECLINED = 'Declined';
    public static final String CREATED_DATE_MORE_THAN_30_DAYS = 'CreatedDate < LAST_N_DAYS:30';
    public static final String EMAIL_SUBJECT_FOR_BATCH = 'Batch Process Completed';
    public static final String EMAIL_SENDER_DISPLAY_NAME_FOR_BATCH = 'Batch Processing';
    public static final String RESPONSE_BODY_PARAMETER_NAME_EMPTY = 'The name must be not empty.';
    public static final String RESPONSE_BODY_PARAMETER_AGE_NOT_INTEGER = 'The age must be a number.';
    public static final String RESPONSE_BODY_RECORDS_EXISTS = 'Records exists.';
    public static final String RESPONSE_BODY_INTERNAL_SERVER_ERROR = 'Internal server error';
    public static final String REQUEST_HEADER_VALUE_RAPIDAPI_KEY = 'a931a01d22msh844c1c9ac0000e9p11d62bjsnb01ea37dd1f1';
    public static final String HTTP_METHOD_GET = 'GET';
    public static final Integer RESPONSE_STATUS_CODE_500 = 500;
    public static final Integer RESPONSE_STATUS_CODE_200 = 200;
    public static final Integer RESPONSE_STATUS_CODE_404 = 404;
    public static final Integer RESPONSE_STATUS_CODE_409 = 409;
}
